name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies (including dev)
      - run: npm install --include=dev

      # Build Vite
      - run: npm run build

      # Deploy Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_RANKSPRINTAI_1EFF8 }}"
          channelId: live
          projectId: ranksprintai-1eff8
